[workspace]
resolver = "2"
members = [
  "packages/rust/bins/cli",
  "packages/rust/bins/docs",
  "packages/rust/crates/check",
  "packages/rust/crates/ui",
  "packages/rust/crates/content",
  "packages/rust/crates/model",
  "packages/rust/crates/review",
  "packages/rust/crates/scanning",
  "packages/rust/crates/workspace",
]
