[workspace]
resolver = "2"
members = [
  "packages/rust/bins/cli",
  "packages/rust/bins/docs",
  "packages/rust/libs/cli/cli-app",
  "packages/rust/libs/cli/cli-output",
  "packages/rust/libs/cli/cli-parser",
  "packages/rust/libs/cli/cli-types",
  "packages/rust/libs/cli/init",
  "packages/rust/libs/cli/check-command",
  "packages/rust/libs/cli/review",
  "packages/rust/libs/cli/sync",
  "packages/rust/libs/docs/content",
  "packages/rust/libs/docs/docs-server",
  "packages/rust/libs/docs/ui",
  "packages/rust/libs/shared/check",
  "packages/rust/libs/shared/model",
  "packages/rust/libs/shared/scanning",
  "packages/rust/libs/shared/test-macros",
  "packages/rust/libs/shared/workspace",
]

[workspace.dependencies]
bloomery-test-macros = { path = "packages/rust/libs/shared/test-macros" }
