use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs::{self, File, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

const GENERATED_HEADER: &str = "# This file is automatically @generated by Bloomery.\n# It is not intended for manual editing.\n";
static TEMP_FILE_COUNTER: AtomicU64 = AtomicU64::new(0);

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub(crate) struct BloomeryLock {
    pub version: u32,
    #[serde(rename = "cargo-lock-hash")]
    pub cargo_lock_hash: String,
    pub packages: BTreeMap<String, BloomeryPackage>,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub(crate) struct BloomeryPackage {
    pub features: Vec<String>,
    pub dependencies: Vec<String>,
    #[serde(rename = "proc-macro")]
    pub proc_macro: bool,
    pub edition: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PublicationOutcome {
    Written,
    Unchanged,
}

pub(crate) fn serialize_candidate(lock: &BloomeryLock) -> Result<Vec<u8>, String> {
    validate_lock(lock)?;
    let body = toml::to_string_pretty(lock)
        .map_err(|error| format!("unable to serialize bloomery.lock candidate: {error}"))?;
    let candidate = format!("{GENERATED_HEADER}{body}");

    let parsed: BloomeryLock = toml::from_str(&candidate)
        .map_err(|error| format!("serialized bloomery.lock candidate is invalid TOML: {error}"))?;
    if parsed != *lock {
        return Err("serialized bloomery.lock candidate failed its data validation".to_owned());
    }

    Ok(candidate.into_bytes())
}

fn validate_lock(lock: &BloomeryLock) -> Result<(), String> {
    if lock.version != 1 {
        return Err(format!(
            "unsupported Bloomery lock version {}; expected version 1",
            lock.version
        ));
    }
    if lock.cargo_lock_hash.len() != 64
        || !lock
            .cargo_lock_hash
            .bytes()
            .all(|character| character.is_ascii_hexdigit() && !character.is_ascii_uppercase())
    {
        return Err("cargo-lock-hash must be a 64-character lowercase SHA-256 digest".to_owned());
    }

    for (key, package) in &lock.packages {
        if key.is_empty() {
            return Err("Bloomery lock package keys must not be empty".to_owned());
        }
        if package.edition.is_empty() {
            return Err(format!("package '{key}' has an empty edition"));
        }
        if !is_strictly_sorted(&package.features) {
            return Err(format!(
                "package '{key}' features must be sorted and deduplicated"
            ));
        }
        if !is_strictly_sorted(&package.dependencies) {
            return Err(format!(
                "package '{key}' dependencies must be sorted and deduplicated"
            ));
        }
        for dependency in &package.dependencies {
            if !lock.packages.contains_key(dependency) {
                return Err(format!(
                    "package '{key}' references unresolved Bloomery lock dependency '{dependency}'"
                ));
            }
        }
    }
    Ok(())
}

fn is_strictly_sorted(values: &[String]) -> bool {
    values.windows(2).all(|pair| pair[0] < pair[1])
}

pub(crate) fn publish_candidate(
    target: &Path,
    candidate: &[u8],
) -> Result<PublicationOutcome, String> {
    publish_candidate_with(
        target,
        candidate,
        |file, bytes| file.write_all(bytes),
        |source, destination| fs::rename(source, destination),
    )
}

fn publish_candidate_with<W, R>(
    target: &Path,
    candidate: &[u8],
    write_candidate: W,
    rename: R,
) -> Result<PublicationOutcome, String>
where
    W: FnOnce(&mut File, &[u8]) -> io::Result<()>,
    R: FnOnce(&Path, &Path) -> io::Result<()>,
{
    match fs::read(target) {
        Ok(existing) if existing == candidate => return Ok(PublicationOutcome::Unchanged),
        Ok(_) => {}
        Err(error) if error.kind() == io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(format!(
                "unable to read existing Bloomery lock '{}': {error}",
                target.display()
            ));
        }
    }

    let (mut file, temporary_path) = create_sibling_temp(target).map_err(|error| {
        format!(
            "unable to create a temporary Bloomery lock beside '{}': {error}",
            target.display()
        )
    })?;
    let mut guard = TempFileGuard::new(temporary_path);

    let write_result = write_candidate(&mut file, candidate).and_then(|()| file.sync_all());
    drop(file);
    write_result.map_err(|error| {
        format!(
            "unable to write temporary Bloomery lock '{}': {error}",
            guard.path.display()
        )
    })?;

    rename(&guard.path, target).map_err(|error| {
        format!(
            "unable to atomically publish Bloomery lock '{}': {error}",
            target.display()
        )
    })?;
    guard.published = true;
    Ok(PublicationOutcome::Written)
}

fn create_sibling_temp(target: &Path) -> io::Result<(File, PathBuf)> {
    let parent = target
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."));
    let file_name = target.file_name().ok_or_else(|| {
        io::Error::new(
            io::ErrorKind::InvalidInput,
            "Bloomery lock target has no file name",
        )
    })?;

    for _ in 0..128 {
        let counter = TEMP_FILE_COUNTER.fetch_add(1, Ordering::Relaxed);
        let mut temporary_name = std::ffi::OsString::from(".");
        temporary_name.push(file_name);
        temporary_name.push(format!(".{}.{}.tmp", std::process::id(), counter));
        let path = parent.join(temporary_name);
        match OpenOptions::new().write(true).create_new(true).open(&path) {
            Ok(file) => return Ok((file, path)),
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        }
    }
    Err(io::Error::new(
        io::ErrorKind::AlreadyExists,
        "could not allocate a unique temporary file name",
    ))
}

struct TempFileGuard {
    path: PathBuf,
    published: bool,
}

impl TempFileGuard {
    fn new(path: PathBuf) -> Self {
        Self {
            path,
            published: false,
        }
    }
}

impl Drop for TempFileGuard {
    fn drop(&mut self) {
        if !self.published {
            let _ = fs::remove_file(&self.path);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{
        BloomeryLock, BloomeryPackage, PublicationOutcome, publish_candidate,
        publish_candidate_with, serialize_candidate,
    };
    use std::collections::BTreeMap;
    use std::fs;
    use std::io::{self, Write};
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU64, Ordering};

    static FIXTURE_COUNTER: AtomicU64 = AtomicU64::new(0);

    struct Fixture {
        root: PathBuf,
    }

    impl Fixture {
        fn new() -> Self {
            let suffix = FIXTURE_COUNTER.fetch_add(1, Ordering::Relaxed);
            let root = std::env::temp_dir().join(format!(
                "bloomery-sync-lock-{}-{suffix}",
                std::process::id()
            ));
            fs::create_dir_all(&root).expect("fixture directory");
            Self { root }
        }

        fn lock(&self) -> PathBuf {
            self.root.join("bloomery.lock")
        }
    }

    impl Drop for Fixture {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    fn sample_lock() -> BloomeryLock {
        BloomeryLock {
            version: 1,
            cargo_lock_hash: "a".repeat(64),
            packages: BTreeMap::from([
                (
                    "crate-a-1.0.0".to_owned(),
                    BloomeryPackage {
                        features: vec!["alpha".to_owned(), "zeta".to_owned()],
                        dependencies: vec!["crate-b-2.0.0".to_owned()],
                        proc_macro: false,
                        edition: "2024".to_owned(),
                    },
                ),
                (
                    "crate-b-2.0.0".to_owned(),
                    BloomeryPackage {
                        features: Vec::new(),
                        dependencies: Vec::new(),
                        proc_macro: true,
                        edition: "2021".to_owned(),
                    },
                ),
            ]),
        }
    }

    fn temporary_files(root: &std::path::Path) -> Vec<PathBuf> {
        fs::read_dir(root)
            .expect("read fixture")
            .map(|entry| entry.expect("directory entry").path())
            .filter(|path| {
                path.file_name()
                    .is_some_and(|name| name.to_string_lossy().ends_with(".tmp"))
            })
            .collect()
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-004"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-005"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-006"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-019"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-020"))]
    fn candidate_is_a_valid_version_one_lock_with_sorted_tables_and_fields() {
        let candidate = serialize_candidate(&sample_lock()).expect("serialized candidate");
        let text = String::from_utf8(candidate.clone()).expect("UTF-8 TOML");
        assert!(text.starts_with(
            "# This file is automatically @generated by Bloomery.\n# It is not intended for manual editing.\n"
        ));
        assert!(text.contains("version = 1\n"));
        assert!(text.contains("cargo-lock-hash = \""));
        assert!(
            text.find("[packages.\"crate-a-1.0.0\"]").unwrap()
                < text.find("[packages.\"crate-b-2.0.0\"]").unwrap()
        );
        assert!(text.contains("features = [\n    \"alpha\",\n    \"zeta\",\n]"));
        assert!(text.contains("dependencies = [\"crate-b-2.0.0\"]"));
        assert!(toml::from_str::<BloomeryLock>(&text).is_ok());

        let mut invalid = sample_lock();
        invalid
            .packages
            .get_mut("crate-a-1.0.0")
            .expect("package")
            .features = vec!["zeta".to_owned(), "alpha".to_owned()];
        assert!(
            serialize_candidate(&invalid)
                .expect_err("unsorted candidate")
                .contains("sorted and deduplicated")
        );
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-021"))]
    fn toml_writer_escapes_package_keys_and_string_values() {
        let mut lock = sample_lock();
        lock.packages.clear();
        let unusual_key = "crate.\\\"name-1.0.0".to_owned();
        let unusual_feature = "quote: \" slash: \\".to_owned();
        lock.packages.insert(
            unusual_key.clone(),
            BloomeryPackage {
                features: vec![unusual_feature.clone()],
                dependencies: Vec::new(),
                proc_macro: false,
                edition: "2021".to_owned(),
            },
        );
        let candidate = serialize_candidate(&lock).expect("escaped lock");
        let text = String::from_utf8(candidate).expect("UTF-8 TOML");
        let parsed: BloomeryLock = toml::from_str(&text).expect("valid escaped TOML");
        assert_eq!(parsed.packages[&unusual_key].features, [unusual_feature]);
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-023"))]
    fn publication_writes_a_sibling_temporary_file_then_atomically_renames_it() {
        let fixture = Fixture::new();
        let target = fixture.lock();
        let candidate = serialize_candidate(&sample_lock()).expect("candidate");

        assert_eq!(
            publish_candidate(&target, &candidate).expect("publish"),
            PublicationOutcome::Written
        );
        assert_eq!(fs::read(&target).expect("published bytes"), candidate);
        assert!(temporary_files(&fixture.root).is_empty());
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-024"))]
    fn identical_lock_bytes_leave_the_existing_file_untouched() {
        let fixture = Fixture::new();
        let target = fixture.lock();
        let candidate = serialize_candidate(&sample_lock()).expect("candidate");
        fs::write(&target, &candidate).expect("existing lock");
        #[cfg(unix)]
        let inode = {
            use std::os::unix::fs::MetadataExt;
            fs::metadata(&target).expect("metadata").ino()
        };

        assert_eq!(
            publish_candidate(&target, &candidate).expect("unchanged publish"),
            PublicationOutcome::Unchanged
        );
        assert_eq!(fs::read(&target).expect("lock bytes"), candidate);
        #[cfg(unix)]
        {
            use std::os::unix::fs::MetadataExt;
            assert_eq!(fs::metadata(&target).expect("metadata").ino(), inode);
        }
        assert!(temporary_files(&fixture.root).is_empty());
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-025"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-026"))]
    fn failed_partial_write_preserves_the_old_lock_and_cleans_up_the_temp_file() {
        let fixture = Fixture::new();
        let target = fixture.lock();
        let previous = b"previous bloomery lock";
        fs::write(&target, previous).expect("existing lock");
        let candidate = serialize_candidate(&sample_lock()).expect("candidate");

        let error = publish_candidate_with(
            &target,
            &candidate,
            |file, bytes| {
                file.write_all(&bytes[..bytes.len() / 2])?;
                Err(io::Error::other("injected disk write failure"))
            },
            |source, destination| fs::rename(source, destination),
        )
        .expect_err("injected write failure");
        assert!(error.contains("injected disk write failure"));
        assert_eq!(fs::read(&target).expect("old lock remains"), previous);
        assert!(temporary_files(&fixture.root).is_empty());
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-025"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-026"))]
    fn failed_atomic_rename_preserves_the_old_lock_and_cleans_up_the_temp_file() {
        let fixture = Fixture::new();
        let target = fixture.lock();
        let previous = b"previous bloomery lock";
        fs::write(&target, previous).expect("existing lock");
        let candidate = serialize_candidate(&sample_lock()).expect("candidate");

        let error = publish_candidate_with(
            &target,
            &candidate,
            |file, bytes| file.write_all(bytes),
            |_source, _destination| Err(io::Error::other("injected rename failure")),
        )
        .expect_err("injected rename failure");
        assert!(error.contains("injected rename failure"));
        assert_eq!(fs::read(&target).expect("old lock remains"), previous);
        assert!(temporary_files(&fixture.root).is_empty());
    }

    #[test]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-025"))]
    #[cfg_attr(any(), bloomery("CLI-SYNC-LOCKS-026"))]
    fn failed_first_publication_leaves_no_lock_or_temporary_file() {
        let fixture = Fixture::new();
        let target = fixture.lock();
        let candidate = serialize_candidate(&sample_lock()).expect("candidate");

        let result = publish_candidate_with(
            &target,
            &candidate,
            |_file, _bytes| Err(io::Error::other("injected write failure")),
            |source, destination| fs::rename(source, destination),
        );
        assert!(result.is_err());
        assert!(!target.exists());
        assert!(temporary_files(&fixture.root).is_empty());
    }
}
