# Generated by bloomery. DO NOT EDIT.
{
  version = 1;
  cargoLockHash = "94d3ebfd1f128c79b29bf084ca438fb2f61f4fe9d35905df2f0c2691913df7db";
  packages = {
    "bin-calc-0.1.0" = {
      features = [ ];
      dependencies = [ "lib-calc-0.1.0" "lib-core-0.1.0" ];
      procMacro = false;
      edition = "2021";
    };
    "bin-report-0.1.0" = {
      features = [ ];
      dependencies = [ "lib-calc-0.1.0" "lib-msg-0.1.0" ];
      procMacro = false;
      edition = "2021";
    };
    "itoa-1.0.18" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "lib-calc-0.1.0" = {
      features = [ ];
      dependencies = [ "lib-core-0.1.0" ];
      procMacro = false;
      edition = "2021";
    };
    "lib-core-0.1.0" = {
      features = [ ];
      dependencies = [ "itoa-1.0.18" ];
      procMacro = false;
      edition = "2021";
    };
    "lib-msg-0.1.0" = {
      features = [ ];
      dependencies = [ "lib-core-0.1.0" ];
      procMacro = false;
      edition = "2021";
    };
  };
}

