[dependencies]
app_ui = { package = "{{project}}_ui", path = "../{{project}}_ui" }
tokio = { version = "1", default-features = false, features = [
  "net",
  "rt-multi-thread",
] }
topcoat = { version = "0.9.0", default-features = false, features = [
  "asset",
  "compression",
  "router",
  "serve",
  "view",
] }

[package]
name = "{{project}}_server"
version = "0.1.0"
edition = "2024"
