{ pkgs, lib ? pkgs.lib }:

let
  lockScript = pkgs.writeShellApplication {
    name = "bloomery-lock";
    runtimeInputs = [ pkgs.cargo pkgs.jq pkgs.coreutils ];
    text = ''
      set -euo pipefail

      TARGET_DIR="''${1:-.}"
      CARGO_LOCK="$TARGET_DIR/Cargo.lock"
      CARGO_TOML="$TARGET_DIR/Cargo.toml"
      OUTPUT_LOCK="$TARGET_DIR/bloomery.lock.nix"

      if [ ! -f "$CARGO_LOCK" ]; then
        echo "Error: Cargo.lock not found at $CARGO_LOCK." >&2
        exit 1
      fi

      if [ ! -f "$CARGO_TOML" ]; then
        echo "Error: Cargo.toml not found at $CARGO_TOML." >&2
        exit 1
      fi

      echo "==> Resolving features and dependencies via cargo metadata..."
      LOCK_HASH=$(sha256sum "$CARGO_LOCK" | awk '{print $1}')

      METADATA=$(cargo metadata --manifest-path "$CARGO_TOML" --format-version 1)

      echo "==> Generating $OUTPUT_LOCK..."
      echo "$METADATA" | jq -r --arg hash "$LOCK_HASH" '
        (.packages | map({key: .id, value: .}) | from_entries) as $pkgMap |
        "# Generated by bloomery. DO NOT EDIT.\n{\n  version = 1;\n  cargoLockHash = \"" + $hash + "\";\n  packages = {" +
        (
          .resolve.nodes | map(
            $pkgMap[.id] as $pkg |
            ($pkg.name + "-" + $pkg.version) as $pkgId |
            ($pkg.targets | any(.kind[] == "proc-macro")) as $isProcMacro |
            (
              "\n    \"" + $pkgId + "\" = {\n" +
              "      features = [ " + (.features | map("\"" + . + "\"") | join(" ")) + (if (.features | length) > 0 then " " else "" end) + "];\n" +
              "      dependencies = [ " + ([.deps[] | $pkgMap[.pkg] | ("\"" + .name + "-" + .version + "\"")] | join(" ")) + (if (.deps | length) > 0 then " " else "" end) + "];\n" +
              "      procMacro = " + (if $isProcMacro then "true" else "false" end) + ";\n" +
              "      edition = \"" + ($pkg.edition // "2021") + "\";\n" +
              "    };"
            )
          ) | join("")
        ) + "\n  };\n}\n"
      ' > "$OUTPUT_LOCK"

      echo "==> Successfully wrote $OUTPUT_LOCK."
    '';
  };
in {
  inherit lockScript;
}
