# Generated by bloomery. DO NOT EDIT.
{
  version = 1;
  cargoLockHash = "3e65557006a6df17321da83ec1b31875c6d9b5d29df216592d88b61adee856fa";
  packages = {
    "adler2-2.0.1" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "aead-0.5.2" = {
      features = [ "alloc" "getrandom" "rand_core" ];
      dependencies = [ "crypto-common-0.1.7" "generic-array-0.14.7" ];
      procMacro = false;
      edition = "2021";
    };
    "aes-0.8.4" = {
      features = [ ];
      dependencies = [ "cfg-if-1.0.5" "cipher-0.4.4" "cpufeatures-0.2.17" ];
      procMacro = false;
      edition = "2021";
    };
    "aes-gcm-0.10.3" = {
      features = [ "aes" "alloc" "default" "getrandom" "rand_core" ];
      dependencies = [ "aead-0.5.2" "aes-0.8.4" "cipher-0.4.4" "ctr-0.9.2" "ghash-0.5.1" "subtle-2.6.1" ];
      procMacro = false;
      edition = "2021";
    };
    "alloc-no-stdlib-2.0.4" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "alloc-stdlib-0.2.4" = {
      features = [ ];
      dependencies = [ "alloc-no-stdlib-2.0.4" ];
      procMacro = false;
      edition = "2015";
    };
    "anymap3-1.1.0" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "async-compression-0.4.48" = {
      features = [ "brotli" "gzip" "tokio" ];
      dependencies = [ "compression-codecs-0.4.43" "compression-core-0.4.33" "pin-project-lite-0.2.17" "tokio-1.53.1" ];
      procMacro = false;
      edition = "2018";
    };
    "atomic-waker-1.1.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "base64-0.22.1" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "base64-0.23.1" = {
      features = [ "alloc" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "bitflags-2.13.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "block-buffer-0.10.4" = {
      features = [ ];
      dependencies = [ "generic-array-0.14.7" ];
      procMacro = false;
      edition = "2018";
    };
    "block-buffer-0.12.1" = {
      features = [ ];
      dependencies = [ "hybrid-array-0.4.15" ];
      procMacro = false;
      edition = "2024";
    };
    "bloomery-docs-0.1.0" = {
      features = [ ];
      dependencies = [ "tokio-1.53.1" "topcoat-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "brotli-8.0.4" = {
      features = [ "alloc-stdlib" "default" "std" ];
      dependencies = [ "alloc-no-stdlib-2.0.4" "alloc-stdlib-0.2.4" "brotli-decompressor-5.0.3" ];
      procMacro = false;
      edition = "2015";
    };
    "brotli-decompressor-5.0.3" = {
      features = [ "alloc-stdlib" "std" ];
      dependencies = [ "alloc-no-stdlib-2.0.4" "alloc-stdlib-0.2.4" ];
      procMacro = false;
      edition = "2015";
    };
    "bumpalo-3.20.3" = {
      features = [ "default" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "bytes-1.12.1" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "cfg-if-1.0.5" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "cipher-0.4.4" = {
      features = [ ];
      dependencies = [ "crypto-common-0.1.7" "inout-0.1.4" ];
      procMacro = false;
      edition = "2021";
    };
    "compression-codecs-0.4.43" = {
      features = [ "brotli" "flate2" "gzip" "memchr" ];
      dependencies = [ "brotli-8.0.4" "compression-core-0.4.33" "flate2-1.1.10" "memchr-2.8.3" ];
      procMacro = false;
      edition = "2018";
    };
    "compression-core-0.4.33" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "const-oid-0.10.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "cookie-0.18.2" = {
      features = [ "aes-gcm" "base64" "hkdf" "hmac" "key-expansion" "percent-encode" "percent-encoding" "private" "rand" "secure" "sha2" "signed" "subtle" ];
      dependencies = [ "aes-gcm-0.10.3" "base64-0.22.1" "hkdf-0.12.4" "hmac-0.12.1" "percent-encoding-2.3.2" "rand-0.8.8" "sha2-0.10.9" "subtle-2.6.1" "time-0.3.55" "version_check-0.9.5" ];
      procMacro = false;
      edition = "2018";
    };
    "cpufeatures-0.2.17" = {
      features = [ ];
      dependencies = [ "libc-0.2.189" ];
      procMacro = false;
      edition = "2018";
    };
    "cpufeatures-0.3.1" = {
      features = [ ];
      dependencies = [ "libc-0.2.189" ];
      procMacro = false;
      edition = "2024";
    };
    "crc32fast-1.5.2" = {
      features = [ "std" ];
      dependencies = [ "cfg-if-1.0.5" ];
      procMacro = false;
      edition = "2021";
    };
    "crypto-common-0.1.7" = {
      features = [ "getrandom" "rand_core" "std" ];
      dependencies = [ "generic-array-0.14.7" "rand_core-0.6.4" "typenum-1.20.1" ];
      procMacro = false;
      edition = "2018";
    };
    "crypto-common-0.2.2" = {
      features = [ ];
      dependencies = [ "hybrid-array-0.4.15" ];
      procMacro = false;
      edition = "2024";
    };
    "ctr-0.9.2" = {
      features = [ ];
      dependencies = [ "cipher-0.4.4" ];
      procMacro = false;
      edition = "2021";
    };
    "data-encoding-2.11.1" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "deranged-0.5.8" = {
      features = [ "default" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "digest-0.10.7" = {
      features = [ "alloc" "block-buffer" "core-api" "default" "mac" "std" "subtle" ];
      dependencies = [ "block-buffer-0.10.4" "crypto-common-0.1.7" "subtle-2.6.1" ];
      procMacro = false;
      edition = "2018";
    };
    "digest-0.11.3" = {
      features = [ "alloc" "block-api" "default" "oid" ];
      dependencies = [ "block-buffer-0.12.1" "const-oid-0.10.2" "crypto-common-0.2.2" ];
      procMacro = false;
      edition = "2024";
    };
    "displaydoc-0.2.7" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "elsa-1.11.2" = {
      features = [ "default" ];
      dependencies = [ "stable_deref_trait-1.2.1" ];
      procMacro = false;
      edition = "2018";
    };
    "email-encoding-0.4.2" = {
      features = [ "default" "std" ];
      dependencies = [ "base64-0.23.1" "memchr-2.8.3" ];
      procMacro = false;
      edition = "2024";
    };
    "email_address-0.2.9" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "equivalent-1.0.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "errno-0.3.14" = {
      features = [ "default" "std" ];
      dependencies = [ "libc-0.2.189" "windows-sys-0.61.2" ];
      procMacro = false;
      edition = "2018";
    };
    "fastrand-2.5.0" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "flate2-1.1.10" = {
      features = [ "any_impl" "default" "miniz_oxide" "runtime_detection" "rust_backend" ];
      dependencies = [ "crc32fast-1.5.2" "miniz_oxide-0.9.1" "zlib-rs-0.6.8" ];
      procMacro = false;
      edition = "2018";
    };
    "fnv-1.0.7" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "form_urlencoded-1.2.2" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ "percent-encoding-2.3.2" ];
      procMacro = false;
      edition = "2018";
    };
    "futures-channel-0.3.34" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ "futures-core-0.3.34" ];
      procMacro = false;
      edition = "2018";
    };
    "futures-core-0.3.34" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "futures-macro-0.3.34" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2018";
    };
    "futures-sink-0.3.34" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "futures-task-0.3.34" = {
      features = [ "alloc" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "futures-util-0.3.34" = {
      features = [ "alloc" "async-await" "async-await-macro" "default" "futures-macro" "futures-sink" "sink" "slab" "std" ];
      dependencies = [ "futures-core-0.3.34" "futures-macro-0.3.34" "futures-sink-0.3.34" "futures-task-0.3.34" "pin-project-lite-0.2.17" "slab-0.4.12" ];
      procMacro = false;
      edition = "2018";
    };
    "generic-array-0.14.7" = {
      features = [ "more_lengths" ];
      dependencies = [ "typenum-1.20.1" "version_check-0.9.5" ];
      procMacro = false;
      edition = "2015";
    };
    "getrandom-0.2.17" = {
      features = [ "js" "js-sys" "std" "wasm-bindgen" ];
      dependencies = [ "cfg-if-1.0.5" "js-sys-0.3.106" "libc-0.2.189" "wasi-0.11.1+wasi-snapshot-preview1" "wasm-bindgen-0.2.129" ];
      procMacro = false;
      edition = "2018";
    };
    "getrandom-0.3.4" = {
      features = [ "std" ];
      dependencies = [ "cfg-if-1.0.5" "libc-0.2.189" "r-efi-5.3.0" "wasip2-1.0.4+wasi-0.2.12" ];
      procMacro = false;
      edition = "2021";
    };
    "getrandom-0.4.3" = {
      features = [ "wasm_js" ];
      dependencies = [ "cfg-if-1.0.5" "js-sys-0.3.106" "libc-0.2.189" "r-efi-6.0.0" "wasm-bindgen-0.2.129" ];
      procMacro = false;
      edition = "2024";
    };
    "ghash-0.5.1" = {
      features = [ ];
      dependencies = [ "opaque-debug-0.3.1" "polyval-0.6.2" ];
      procMacro = false;
      edition = "2021";
    };
    "h2-0.4.19" = {
      features = [ ];
      dependencies = [ "atomic-waker-1.1.2" "bytes-1.12.1" "fnv-1.0.7" "futures-core-0.3.34" "futures-sink-0.3.34" "http-1.5.0" "indexmap-2.14.2" "slab-0.4.12" "tokio-1.53.1" "tokio-util-0.7.19" "tracing-0.1.44" ];
      procMacro = false;
      edition = "2021";
    };
    "hashbrown-0.17.1" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "heck-0.5.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "hkdf-0.12.4" = {
      features = [ ];
      dependencies = [ "hmac-0.12.1" ];
      procMacro = false;
      edition = "2018";
    };
    "hmac-0.12.1" = {
      features = [ ];
      dependencies = [ "digest-0.10.7" ];
      procMacro = false;
      edition = "2018";
    };
    "hostname-0.4.2" = {
      features = [ "default" ];
      dependencies = [ "cfg-if-1.0.5" "libc-0.2.189" "windows-link-0.2.1" ];
      procMacro = false;
      edition = "2021";
    };
    "http-1.5.0" = {
      features = [ "default" "std" ];
      dependencies = [ "bytes-1.12.1" "itoa-1.0.18" ];
      procMacro = false;
      edition = "2021";
    };
    "http-body-1.1.0" = {
      features = [ ];
      dependencies = [ "bytes-1.12.1" "http-1.5.0" ];
      procMacro = false;
      edition = "2018";
    };
    "http-body-util-0.1.5" = {
      features = [ "default" ];
      dependencies = [ "bytes-1.12.1" "futures-core-0.3.34" "http-1.5.0" "http-body-1.1.0" "pin-project-lite-0.2.17" ];
      procMacro = false;
      edition = "2018";
    };
    "httparse-1.10.1" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "httpdate-1.0.3" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "hybrid-array-0.4.15" = {
      features = [ ];
      dependencies = [ "typenum-1.20.1" ];
      procMacro = false;
      edition = "2024";
    };
    "hyper-1.11.1" = {
      features = [ "default" "http1" "http2" "server" ];
      dependencies = [ "atomic-waker-1.1.2" "bytes-1.12.1" "futures-channel-0.3.34" "futures-core-0.3.34" "h2-0.4.19" "http-1.5.0" "http-body-1.1.0" "httparse-1.10.1" "httpdate-1.0.3" "itoa-1.0.18" "pin-project-lite-0.2.17" "smallvec-1.16.2" "tokio-1.53.1" ];
      procMacro = false;
      edition = "2021";
    };
    "hyper-util-0.1.21" = {
      features = [ "default" "http1" "http2" "server" "server-auto" "tokio" ];
      dependencies = [ "bytes-1.12.1" "http-1.5.0" "http-body-1.1.0" "hyper-1.11.1" "pin-project-lite-0.2.17" "tokio-1.53.1" ];
      procMacro = false;
      edition = "2024";
    };
    "icu_collections-2.3.0" = {
      features = [ ];
      dependencies = [ "displaydoc-0.2.7" "potential_utf-0.1.6" "utf8_iter-1.0.4" "yoke-0.8.3" "zerofrom-0.1.8" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2024";
    };
    "icu_locale_core-2.3.0" = {
      features = [ "zerovec" ];
      dependencies = [ "displaydoc-0.2.7" "litemap-0.8.3" "tinystr-0.8.4" "writeable-0.6.4" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2024";
    };
    "icu_normalizer-2.3.0" = {
      features = [ "compiled_data" ];
      dependencies = [ "icu_collections-2.3.0" "icu_normalizer_data-2.3.0" "icu_properties-2.3.0" "icu_provider-2.3.1" "smallvec-1.16.2" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2024";
    };
    "icu_normalizer_data-2.3.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "icu_properties-2.3.0" = {
      features = [ "compiled_data" ];
      dependencies = [ "displaydoc-0.2.7" "icu_collections-2.3.0" "icu_locale_core-2.3.0" "icu_properties_data-2.3.0" "icu_provider-2.3.1" "zerotrie-0.2.5" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2024";
    };
    "icu_properties_data-2.3.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "icu_provider-2.3.1" = {
      features = [ "baked" ];
      dependencies = [ "displaydoc-0.2.7" "icu_locale_core-2.3.0" "writeable-0.6.4" "yoke-0.8.3" "zerofrom-0.1.8" "zerotrie-0.2.5" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2024";
    };
    "idna-1.1.0" = {
      features = [ "alloc" "compiled_data" "default" "std" ];
      dependencies = [ "idna_adapter-1.2.2" "smallvec-1.16.2" "utf8_iter-1.0.4" ];
      procMacro = false;
      edition = "2018";
    };
    "idna_adapter-1.2.2" = {
      features = [ "compiled_data" ];
      dependencies = [ "icu_normalizer-2.3.0" "icu_properties-2.3.0" ];
      procMacro = false;
      edition = "2024";
    };
    "indexmap-2.14.2" = {
      features = [ "default" "std" ];
      dependencies = [ "equivalent-1.0.2" "hashbrown-0.17.1" ];
      procMacro = false;
      edition = "2024";
    };
    "inout-0.1.4" = {
      features = [ ];
      dependencies = [ "generic-array-0.14.7" ];
      procMacro = false;
      edition = "2021";
    };
    "ipnet-2.12.2" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "itoa-1.0.18" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "js-sys-0.3.106" = {
      features = [ "default" "std" "unsafe-eval" ];
      dependencies = [ "cfg-if-1.0.5" "futures-util-0.3.34" "wasm-bindgen-0.2.129" ];
      procMacro = false;
      edition = "2021";
    };
    "lettre-0.11.23" = {
      features = [ "builder" "hostname" ];
      dependencies = [ "email-encoding-0.4.2" "email_address-0.2.9" "fastrand-2.5.0" "hostname-0.4.2" "httpdate-1.0.3" "idna-1.1.0" "mime-0.3.17" "nom-8.0.0" "quoted_printable-0.5.2" ];
      procMacro = false;
      edition = "2024";
    };
    "libc-0.2.189" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "litemap-0.8.3" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "log-0.4.34" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "matchit-0.9.2" = {
      features = [ "default" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "memchr-2.8.3" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "mime-0.3.17" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "miniz_oxide-0.9.1" = {
      features = [ "default" "simd" "simd-adler32" "with-alloc" ];
      dependencies = [ "adler2-2.0.1" "simd-adler32-0.3.10" ];
      procMacro = false;
      edition = "2021";
    };
    "mio-1.2.3" = {
      features = [ "net" "os-ext" "os-poll" ];
      dependencies = [ "libc-0.2.189" "wasi-0.11.1+wasi-snapshot-preview1" "windows-sys-0.61.2" ];
      procMacro = false;
      edition = "2021";
    };
    "nom-8.0.0" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ "memchr-2.8.3" ];
      procMacro = false;
      edition = "2021";
    };
    "num-conv-0.2.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "once_cell-1.21.4" = {
      features = [ "alloc" "default" "race" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "opaque-debug-0.3.1" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "percent-encoding-2.3.2" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "pin-project-lite-0.2.17" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "polyval-0.6.2" = {
      features = [ ];
      dependencies = [ "cfg-if-1.0.5" "cpufeatures-0.2.17" "opaque-debug-0.3.1" "universal-hash-0.5.1" ];
      procMacro = false;
      edition = "2021";
    };
    "potential_utf-0.1.6" = {
      features = [ "zerovec" ];
      dependencies = [ "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2021";
    };
    "powerfmt-0.2.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "ppv-lite86-0.2.21" = {
      features = [ "simd" "std" ];
      dependencies = [ "zerocopy-0.8.59" ];
      procMacro = false;
      edition = "2021";
    };
    "proc-macro-crate-3.5.0" = {
      features = [ ];
      dependencies = [ "toml_edit-0.25.15+spec-1.1.0" ];
      procMacro = false;
      edition = "2021";
    };
    "proc-macro2-1.0.107" = {
      features = [ "default" "proc-macro" "span-locations" ];
      dependencies = [ "unicode-ident-1.0.26" ];
      procMacro = false;
      edition = "2021";
    };
    "quote-1.0.47" = {
      features = [ "default" "proc-macro" ];
      dependencies = [ "proc-macro2-1.0.107" ];
      procMacro = false;
      edition = "2021";
    };
    "quoted_printable-0.5.2" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "r-efi-5.3.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "r-efi-6.0.0" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "rand-0.8.8" = {
      features = [ "alloc" "default" "getrandom" "libc" "rand_chacha" "std" "std_rng" ];
      dependencies = [ "libc-0.2.189" "rand_chacha-0.3.1" "rand_core-0.6.4" ];
      procMacro = false;
      edition = "2018";
    };
    "rand-0.9.5" = {
      features = [ "alloc" "default" "os_rng" "small_rng" "std" "std_rng" "thread_rng" ];
      dependencies = [ "rand_chacha-0.9.0" "rand_core-0.9.5" ];
      procMacro = false;
      edition = "2021";
    };
    "rand_chacha-0.3.1" = {
      features = [ "std" ];
      dependencies = [ "ppv-lite86-0.2.21" "rand_core-0.6.4" ];
      procMacro = false;
      edition = "2018";
    };
    "rand_chacha-0.9.0" = {
      features = [ "std" ];
      dependencies = [ "ppv-lite86-0.2.21" "rand_core-0.9.5" ];
      procMacro = false;
      edition = "2021";
    };
    "rand_core-0.6.4" = {
      features = [ "alloc" "getrandom" "std" ];
      dependencies = [ "getrandom-0.2.17" ];
      procMacro = false;
      edition = "2018";
    };
    "rand_core-0.9.5" = {
      features = [ "os_rng" "std" ];
      dependencies = [ "getrandom-0.3.4" ];
      procMacro = false;
      edition = "2021";
    };
    "ref-cast-1.0.27" = {
      features = [ ];
      dependencies = [ "ref-cast-impl-1.0.27" ];
      procMacro = false;
      edition = "2021";
    };
    "ref-cast-impl-1.0.27" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "rustversion-1.0.23" = {
      features = [ ];
      dependencies = [ ];
      procMacro = true;
      edition = "2018";
    };
    "ryu-1.0.23" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "serde-1.0.229" = {
      features = [ "default" "derive" "serde_derive" "std" ];
      dependencies = [ "serde_core-1.0.229" "serde_derive-1.0.229" ];
      procMacro = false;
      edition = "2021";
    };
    "serde_core-1.0.229" = {
      features = [ "alloc" "result" "std" ];
      dependencies = [ "serde_derive-1.0.229" ];
      procMacro = false;
      edition = "2021";
    };
    "serde_derive-1.0.229" = {
      features = [ "default" ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "serde_json-1.0.151" = {
      features = [ "default" "std" ];
      dependencies = [ "itoa-1.0.18" "memchr-2.8.3" "serde-1.0.229" "serde_core-1.0.229" "zmij-1.0.23" ];
      procMacro = false;
      edition = "2021";
    };
    "serde_path_to_error-0.1.20" = {
      features = [ ];
      dependencies = [ "itoa-1.0.18" "serde-1.0.229" "serde_core-1.0.229" ];
      procMacro = false;
      edition = "2021";
    };
    "serde_spanned-1.1.1" = {
      features = [ "alloc" "serde" "std" ];
      dependencies = [ "serde_core-1.0.229" ];
      procMacro = false;
      edition = "2024";
    };
    "serde_urlencoded-0.7.1" = {
      features = [ ];
      dependencies = [ "form_urlencoded-1.2.2" "itoa-1.0.18" "ryu-1.0.23" "serde-1.0.229" ];
      procMacro = false;
      edition = "2018";
    };
    "sha1-0.10.7" = {
      features = [ "default" "std" ];
      dependencies = [ "cfg-if-1.0.5" "cpufeatures-0.2.17" "digest-0.10.7" ];
      procMacro = false;
      edition = "2018";
    };
    "sha2-0.10.9" = {
      features = [ "default" "std" ];
      dependencies = [ "cfg-if-1.0.5" "cpufeatures-0.2.17" "digest-0.10.7" ];
      procMacro = false;
      edition = "2018";
    };
    "sha2-0.11.0" = {
      features = [ "alloc" "default" "oid" ];
      dependencies = [ "cfg-if-1.0.5" "cpufeatures-0.3.1" "digest-0.11.3" ];
      procMacro = false;
      edition = "2024";
    };
    "signal-hook-registry-1.4.8" = {
      features = [ ];
      dependencies = [ "errno-0.3.14" "libc-0.2.189" ];
      procMacro = false;
      edition = "2015";
    };
    "simd-adler32-0.3.10" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "siphasher-1.0.4" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "slab-0.4.12" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "smallvec-1.16.2" = {
      features = [ "const_generics" "const_new" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "socket2-0.6.5" = {
      features = [ "all" ];
      dependencies = [ "libc-0.2.189" "windows-sys-0.61.2" ];
      procMacro = false;
      edition = "2021";
    };
    "stable_deref_trait-1.2.1" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "subtle-2.6.1" = {
      features = [ "default" "i128" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "syn-2.0.119" = {
      features = [ "clone-impls" "default" "derive" "full" "parsing" "printing" "proc-macro" ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "unicode-ident-1.0.26" ];
      procMacro = false;
      edition = "2021";
    };
    "syn-3.0.6" = {
      features = [ "clone-impls" "default" "derive" "extra-traits" "fold" "full" "parsing" "printing" "proc-macro" "visit" "visit-mut" ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "unicode-ident-1.0.26" ];
      procMacro = false;
      edition = "2021";
    };
    "sync_wrapper-1.0.2" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "synstructure-0.14.0" = {
      features = [ "default" "proc-macro" ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = false;
      edition = "2018";
    };
    "thiserror-2.0.21" = {
      features = [ "default" "std" ];
      dependencies = [ "thiserror-impl-2.0.21" ];
      procMacro = false;
      edition = "2021";
    };
    "thiserror-impl-2.0.21" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "time-0.3.55" = {
      features = [ "alloc" "default" "formatting" "macros" "parsing" "std" ];
      dependencies = [ "deranged-0.5.8" "num-conv-0.2.2" "powerfmt-0.2.0" "serde_core-1.0.229" "time-core-0.1.9" "time-macros-0.2.32" ];
      procMacro = false;
      edition = "2024";
    };
    "time-core-0.1.9" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "time-macros-0.2.32" = {
      features = [ "formatting" "parsing" ];
      dependencies = [ "num-conv-0.2.2" "time-core-0.1.9" ];
      procMacro = true;
      edition = "2024";
    };
    "tinystr-0.8.4" = {
      features = [ "zerovec" ];
      dependencies = [ "displaydoc-0.2.7" "zerovec-0.11.8" ];
      procMacro = false;
      edition = "2021";
    };
    "tokio-1.53.1" = {
      features = [ "bytes" "default" "fs" "io-util" "libc" "macros" "mio" "net" "rt" "rt-multi-thread" "signal" "signal-hook-registry" "socket2" "sync" "time" "tokio-macros" "windows-sys" ];
      dependencies = [ "bytes-1.12.1" "libc-0.2.189" "mio-1.2.3" "pin-project-lite-0.2.17" "signal-hook-registry-1.4.8" "socket2-0.6.5" "tokio-macros-2.7.2" "windows-sys-0.61.2" ];
      procMacro = false;
      edition = "2021";
    };
    "tokio-macros-2.7.2" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "tokio-tungstenite-0.29.0" = {
      features = [ "connect" "handshake" "stream" ];
      dependencies = [ "futures-util-0.3.34" "log-0.4.34" "tokio-1.53.1" "tungstenite-0.29.0" ];
      procMacro = false;
      edition = "2018";
    };
    "tokio-util-0.7.19" = {
      features = [ "codec" "default" "io" "libc" ];
      dependencies = [ "bytes-1.12.1" "futures-core-0.3.34" "futures-sink-0.3.34" "libc-0.2.189" "pin-project-lite-0.2.17" "tokio-1.53.1" ];
      procMacro = false;
      edition = "2021";
    };
    "toml-1.1.6+spec-1.1.0" = {
      features = [ "default" "display" "parse" "serde" "std" ];
      dependencies = [ "indexmap-2.14.2" "serde_core-1.0.229" "serde_spanned-1.1.1" "toml_datetime-1.1.1+spec-1.1.0" "toml_parser-1.1.3+spec-1.1.0" "toml_writer-1.1.2+spec-1.1.0" "winnow-1.0.4" ];
      procMacro = false;
      edition = "2024";
    };
    "toml_datetime-1.1.1+spec-1.1.0" = {
      features = [ "alloc" "default" "serde" "std" ];
      dependencies = [ "serde_core-1.0.229" ];
      procMacro = false;
      edition = "2024";
    };
    "toml_edit-0.25.15+spec-1.1.0" = {
      features = [ "parse" ];
      dependencies = [ "indexmap-2.14.2" "toml_datetime-1.1.1+spec-1.1.0" "toml_parser-1.1.3+spec-1.1.0" "winnow-1.0.4" ];
      procMacro = false;
      edition = "2024";
    };
    "toml_parser-1.1.3+spec-1.1.0" = {
      features = [ "alloc" "default" "std" ];
      dependencies = [ "winnow-1.0.4" ];
      procMacro = false;
      edition = "2024";
    };
    "toml_writer-1.1.2+spec-1.1.0" = {
      features = [ "alloc" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-0.9.0" = {
      features = [ "compression" "router" "serve" "view" ];
      dependencies = [ "futures-util-0.3.34" "serde-1.0.229" "tokio-1.53.1" "tokio-tungstenite-0.29.0" "topcoat-asset-0.9.0" "topcoat-cookie-0.9.0" "topcoat-core-0.9.0" "topcoat-core-macro-0.9.0" "topcoat-font-0.9.0" "topcoat-mail-0.9.0" "topcoat-router-0.9.0" "topcoat-router-macro-0.9.0" "topcoat-runtime-0.9.0" "topcoat-session-0.9.0" "topcoat-view-0.9.0" "topcoat-view-macro-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-asset-0.9.0" = {
      features = [ "default" "router" "serve" "view" ];
      dependencies = [ "http-1.5.0" "memchr-2.8.3" "serde-1.0.229" "sha2-0.11.0" "thiserror-2.0.21" "tokio-1.53.1" "toml-1.1.6+spec-1.1.0" "topcoat-core-0.9.0" "topcoat-router-0.9.0" "topcoat-view-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-cookie-0.9.0" = {
      features = [ "router" ];
      dependencies = [ "cookie-0.18.2" "getrandom-0.2.17" "http-1.5.0" "serde-1.0.229" "serde_json-1.0.151" "topcoat-core-0.9.0" "topcoat-router-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-core-0.9.0" = {
      features = [ ];
      dependencies = [ "anymap3-1.1.0" "base64-0.22.1" "elsa-1.11.2" "http-1.5.0" "pin-project-lite-0.2.17" "siphasher-1.0.4" "thiserror-2.0.21" "tokio-1.53.1" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-core-grammar-0.9.0" = {
      features = [ ];
      dependencies = [ "proc-macro-crate-3.5.0" "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-core-macro-0.9.0" = {
      features = [ ];
      dependencies = [ "quote-1.0.47" "syn-3.0.6" "topcoat-core-grammar-0.9.0" ];
      procMacro = true;
      edition = "2024";
    };
    "topcoat-font-0.9.0" = {
      features = [ "router" "view" ];
      dependencies = [ "heck-0.5.0" "serde-1.0.229" "serde_json-1.0.151" "topcoat-asset-0.9.0" "topcoat-core-0.9.0" "topcoat-router-0.9.0" "topcoat-view-0.9.0" "topcoat-view-macro-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-mail-0.9.0" = {
      features = [ "router" ];
      dependencies = [ "lettre-0.11.23" "thiserror-2.0.21" "time-0.3.55" "topcoat-core-0.9.0" "topcoat-router-0.9.0" "topcoat-view-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-router-0.9.0" = {
      features = [ "compression" "serve" "websocket" ];
      dependencies = [ "bytes-1.12.1" "form_urlencoded-1.2.2" "futures-core-0.3.34" "futures-sink-0.3.34" "futures-util-0.3.34" "heck-0.5.0" "http-1.5.0" "http-body-1.1.0" "http-body-util-0.1.5" "hyper-1.11.1" "hyper-util-0.1.21" "ipnet-2.12.2" "matchit-0.9.2" "percent-encoding-2.3.2" "pin-project-lite-0.2.17" "ref-cast-1.0.27" "serde-1.0.229" "serde_json-1.0.151" "serde_path_to_error-0.1.20" "serde_urlencoded-0.7.1" "tokio-1.53.1" "tokio-tungstenite-0.29.0" "topcoat-core-0.9.0" "topcoat-view-0.9.0" "tower-0.5.3" "tower-http-0.7.1" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-router-grammar-0.9.0" = {
      features = [ ];
      dependencies = [ "heck-0.5.0" "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" "topcoat-core-grammar-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-router-macro-0.9.0" = {
      features = [ ];
      dependencies = [ "quote-1.0.47" "syn-3.0.6" "topcoat-router-grammar-0.9.0" ];
      procMacro = true;
      edition = "2024";
    };
    "topcoat-runtime-0.9.0" = {
      features = [ "router" ];
      dependencies = [ "futures-util-0.3.34" "pin-project-lite-0.2.17" "ref-cast-1.0.27" "serde-1.0.229" "serde_json-1.0.151" "tokio-1.53.1" "topcoat-asset-0.9.0" "topcoat-core-0.9.0" "topcoat-router-0.9.0" "topcoat-view-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-session-0.9.0" = {
      features = [ "router" ];
      dependencies = [ "base64-0.22.1" "getrandom-0.4.3" "sha2-0.11.0" "thiserror-2.0.21" "tokio-1.53.1" "topcoat-core-0.9.0" "topcoat-router-0.9.0" "web-time-1.1.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-view-0.9.0" = {
      features = [ "http" ];
      dependencies = [ "futures-core-0.3.34" "futures-util-0.3.34" "http-1.5.0" "memchr-2.8.3" "pin-project-lite-0.2.17" "siphasher-1.0.4" "smallvec-1.16.2" "topcoat-core-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-view-grammar-0.9.0" = {
      features = [ ];
      dependencies = [ "heck-0.5.0" "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" "topcoat-core-grammar-0.9.0" "topcoat-view-0.9.0" ];
      procMacro = false;
      edition = "2024";
    };
    "topcoat-view-macro-0.9.0" = {
      features = [ ];
      dependencies = [ "quote-1.0.47" "syn-3.0.6" "topcoat-view-grammar-0.9.0" ];
      procMacro = true;
      edition = "2024";
    };
    "tower-0.5.3" = {
      features = [ "futures-core" "futures-util" "pin-project-lite" "sync_wrapper" "util" ];
      dependencies = [ "futures-core-0.3.34" "futures-util-0.3.34" "pin-project-lite-0.2.17" "sync_wrapper-1.0.2" "tower-layer-0.3.3" "tower-service-0.3.3" ];
      procMacro = false;
      edition = "2018";
    };
    "tower-http-0.7.1" = {
      features = [ "compression-br" "compression-gzip" "default" "futures-core" "tokio-util" ];
      dependencies = [ "async-compression-0.4.48" "bitflags-2.13.2" "bytes-1.12.1" "futures-core-0.3.34" "http-1.5.0" "http-body-1.1.0" "percent-encoding-2.3.2" "pin-project-lite-0.2.17" "tokio-1.53.1" "tokio-util-0.7.19" "tower-layer-0.3.3" "tower-service-0.3.3" ];
      procMacro = false;
      edition = "2018";
    };
    "tower-layer-0.3.3" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "tower-service-0.3.3" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "tracing-0.1.44" = {
      features = [ "std" ];
      dependencies = [ "pin-project-lite-0.2.17" "tracing-core-0.1.36" ];
      procMacro = false;
      edition = "2018";
    };
    "tracing-core-0.1.36" = {
      features = [ "once_cell" "std" ];
      dependencies = [ "once_cell-1.21.4" ];
      procMacro = false;
      edition = "2018";
    };
    "tungstenite-0.29.0" = {
      features = [ "data-encoding" "handshake" "http" "httparse" "sha1" ];
      dependencies = [ "bytes-1.12.1" "data-encoding-2.11.1" "http-1.5.0" "httparse-1.10.1" "log-0.4.34" "rand-0.9.5" "sha1-0.10.7" "thiserror-2.0.21" ];
      procMacro = false;
      edition = "2021";
    };
    "typenum-1.20.1" = {
      features = [ "const-generics" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "unicode-ident-1.0.26" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "universal-hash-0.5.1" = {
      features = [ ];
      dependencies = [ "crypto-common-0.1.7" "subtle-2.6.1" ];
      procMacro = false;
      edition = "2021";
    };
    "utf8_iter-1.0.4" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "version_check-0.9.5" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2015";
    };
    "wasi-0.11.1+wasi-snapshot-preview1" = {
      features = [ "default" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2018";
    };
    "wasip2-1.0.4+wasi-0.2.12" = {
      features = [ ];
      dependencies = [ "wit-bindgen-0.57.1" ];
      procMacro = false;
      edition = "2021";
    };
    "wasm-bindgen-0.2.129" = {
      features = [ "std" ];
      dependencies = [ "cfg-if-1.0.5" "once_cell-1.21.4" "rustversion-1.0.23" "wasm-bindgen-macro-0.2.129" "wasm-bindgen-shared-0.2.129" ];
      procMacro = false;
      edition = "2021";
    };
    "wasm-bindgen-macro-0.2.129" = {
      features = [ ];
      dependencies = [ "quote-1.0.47" "wasm-bindgen-macro-support-0.2.129" ];
      procMacro = true;
      edition = "2021";
    };
    "wasm-bindgen-macro-support-0.2.129" = {
      features = [ ];
      dependencies = [ "bumpalo-3.20.3" "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" "wasm-bindgen-shared-0.2.129" ];
      procMacro = false;
      edition = "2021";
    };
    "wasm-bindgen-shared-0.2.129" = {
      features = [ ];
      dependencies = [ "unicode-ident-1.0.26" ];
      procMacro = false;
      edition = "2021";
    };
    "web-time-1.1.0" = {
      features = [ ];
      dependencies = [ "js-sys-0.3.106" "wasm-bindgen-0.2.129" ];
      procMacro = false;
      edition = "2021";
    };
    "windows-link-0.2.1" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "windows-sys-0.61.2" = {
      features = [ "Wdk" "Wdk_Foundation" "Wdk_Storage" "Wdk_Storage_FileSystem" "Wdk_System" "Wdk_System_IO" "Win32" "Win32_Foundation" "Win32_Networking" "Win32_Networking_WinSock" "Win32_Security" "Win32_Storage" "Win32_Storage_FileSystem" "Win32_System" "Win32_System_Console" "Win32_System_Diagnostics" "Win32_System_Diagnostics_Debug" "Win32_System_IO" "Win32_System_Pipes" "Win32_System_SystemServices" "Win32_System_Threading" "Win32_System_WindowsProgramming" "default" ];
      dependencies = [ "windows-link-0.2.1" ];
      procMacro = false;
      edition = "2021";
    };
    "winnow-1.0.4" = {
      features = [ "alloc" "ascii" "binary" "default" "parser" "std" ];
      dependencies = [ "memchr-2.8.3" ];
      procMacro = false;
      edition = "2021";
    };
    "wit-bindgen-0.57.1" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2024";
    };
    "writeable-0.6.4" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "yoke-0.8.3" = {
      features = [ "derive" "zerofrom" ];
      dependencies = [ "stable_deref_trait-1.2.1" "yoke-derive-0.8.3" "zerofrom-0.1.8" ];
      procMacro = false;
      edition = "2021";
    };
    "yoke-derive-0.8.3" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" "synstructure-0.14.0" ];
      procMacro = true;
      edition = "2021";
    };
    "zerocopy-0.8.59" = {
      features = [ "simd" ];
      dependencies = [ "zerocopy-derive-0.8.59" ];
      procMacro = false;
      edition = "2021";
    };
    "zerocopy-derive-0.8.59" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-2.0.119" ];
      procMacro = true;
      edition = "2021";
    };
    "zerofrom-0.1.8" = {
      features = [ "derive" ];
      dependencies = [ "zerofrom-derive-0.1.8" ];
      procMacro = false;
      edition = "2021";
    };
    "zerofrom-derive-0.1.8" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" "synstructure-0.14.0" ];
      procMacro = true;
      edition = "2021";
    };
    "zerotrie-0.2.5" = {
      features = [ "yoke" "zerofrom" ];
      dependencies = [ "displaydoc-0.2.7" "yoke-0.8.3" "zerofrom-0.1.8" ];
      procMacro = false;
      edition = "2021";
    };
    "zerovec-0.11.8" = {
      features = [ "derive" "yoke" ];
      dependencies = [ "yoke-0.8.3" "zerofrom-0.1.8" "zerovec-derive-0.11.6" ];
      procMacro = false;
      edition = "2021";
    };
    "zerovec-derive-0.11.6" = {
      features = [ ];
      dependencies = [ "proc-macro2-1.0.107" "quote-1.0.47" "syn-3.0.6" ];
      procMacro = true;
      edition = "2021";
    };
    "zlib-rs-0.6.8" = {
      features = [ "rust-allocator" "std" ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
    "zmij-1.0.23" = {
      features = [ ];
      dependencies = [ ];
      procMacro = false;
      edition = "2021";
    };
  };
}

